[helpers]

[default]
depends = []

[default.files]
"zsh/.zshrc.zim" = "~/.zshrc"
"zsh/.zimrc" = "~/.zimrc"
"zsh/.zshenv" = "~/.zshenv"

[default.variables]

[settings]
default_target_type = "automatic"
